"""added alter column in user model

Revision ID: 1c78c85f9077
Revises: d19ef0edaab1
Create Date: 2024-03-18 13:31:18.500040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c78c85f9077'
down_revision = 'd19ef0edaab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PublicId', sa.String(length=100), nullable=True))
        batch_op.drop_index('Public_Id')
        batch_op.create_unique_constraint(None, ['PublicId'])
        batch_op.drop_column('Public_Id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Public_Id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('Public_Id', ['Public_Id'], unique=True)
        batch_op.drop_column('PublicId')

    # ### end Alembic commands ###
