"""empty message

Revision ID: 251091482e5f
Revises: 
Create Date: 2024-03-12 16:22:17.124978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251091482e5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=100), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('CreatedOn', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('user',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('CreatedOn', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('article')
    # ### end Alembic commands ###
