"""inital migration

Revision ID: 4b6ccdb20559
Revises: 
Create Date: 2024-03-08 12:01:47.152611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6ccdb20559'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_article',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=100), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('CreatedOn', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_article')
    # ### end Alembic commands ###
